apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-u2qg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-u2qg
    app.kubernetes.io/part-of: tkrw-pr712-0075-0032-app
  name: devfile-sample-u2qg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-u2qg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-u2qg
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0032-tenant/tkrw-pr712-0075-0032-app/devfile-sample-u2qg@sha256:96135faf47b02e45f38ec51db8f9406ffe4893f4bf0ad3d4baed68813d54338c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
